final scripts

diff --git a/S3/bashscripts/create-bucket b/S3/bashscripts/create-bucket
--- a/S3/bashscripts/create-bucket
+++ b/S3/bashscripts/create-bucket
@@ -17,3 +17,11 @@ regionName=$2
 
 #https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/create-bucket.html
 aws s3api create-bucket --bucket $bucketName --create-bucket-configuration LocationConstraint=$regionName
+
+# Check if the creation was successful
+if [ $? -eq 0 ]; then
+    echo "the bucket '$bucketName' was successfully created"
+else
+    echo "Failed to create bucket."
+    exit 1
+fi
diff --git a/S3/bashscripts/delete-bucket b/S3/bashscripts/delete-bucket
--- a/S3/bashscripts/delete-bucket
+++ b/S3/bashscripts/delete-bucket
@@ -8,5 +8,20 @@ fi
 
 bucketName=$1
 
+# Confirm with the user before deleting the bucket
+read -p "Are you sure you want to delete the bucket '$bucketName'? (yes/no): " confirm
+if [ "$confirm" != "yes" ]; then
+    echo "Aborted."
+    exit 0
+fi
+
 #https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/delete-bucket.html
+#deleting the bucket
 aws s3api delete-bucket --bucket $bucketName
+
+if [ $? -eq 0 ]; then
+    echo "bucket '$bucketName' deleted."
+else
+    echo "Failed to delete the bucket."
+    exit 1
+fi
diff --git a/S3/bashscripts/put-object b/S3/bashscripts/put-object
--- a/S3/bashscripts/put-object
+++ b/S3/bashscripts/put-object
@@ -1,1 +1,36 @@
 #!/usr/bin/env bash
+
+# Check if the bucket name is provided
+if [ -z "$1" ]; then
+    echo "You should specify the bucket name, e.g., my-bucket-example"
+    exit 1
+fi
+
+# Check if the object file path is provided
+if [ -z "$2" ]; then
+    echo "You should specify the file to put in the bucket, e.g., /path/to/my-file"
+    exit 1
+fi
+
+bucketName="$1"
+filePath="$2"
+
+# Check if the file exists
+if [ ! -f "$filePath" ]; then
+    echo "File not found: $filePath"
+    exit 1
+fi
+
+# Extract filename from the path for S3 key
+fileName=$(basename "$filePath")
+
+# Upload file to S3 bucket
+aws s3api put-object --bucket "$bucketName" --key "$fileName" --body "$filePath"
+
+# Check if the upload was successful
+if [ $? -eq 0 ]; then
+    echo "File '$filePath' successfully uploaded to bucket '$bucketName' as '$fileName'."
+else
+    echo "Failed to upload file to bucket."
+    exit 1
+fi
